import riot from 'riot';
import 'riot-hot-reload';
import './tags/cog.tag';
import './tags/nospeech.tag';
import './tags/playbutton.tag';
import './tags/share_link.tag';
import './tags/speakout_progress.tag';
import './tags/stopbutton.tag';
import './tags/speakout_app.tag';
riot.mount('speakout-app');
